import Head from 'next/head'
import { Inter } from 'next/font/google'

import { Box, Container } from '@chakra-ui/react'
import { AppShell, Sidebar, SidebarSection, NavItem } from '@saas-ui/react';
import { AddMonster } from '@/components/addMonster';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container w={'100vw'} h={'100vh'}>


        <AppShell
          navbar={
            <Box as="header" borderBottomWidth="1px" py="2" px="4">
              Logo
            </Box>
          }
          sidebar={
            <Sidebar>
              <SidebarSection>
                <NavItem>Home</NavItem>
                <NavItem>Settings</NavItem>
              </SidebarSection>
            </Sidebar>
          }
        >
          <AddMonster />
        </AppShell>
      </Container>
    </>
  )
}
