import React from 'react';
import Head from 'next/head';

import { Box, Container } from '@chakra-ui/react';
import { AddMonster } from '@/components/addMonster';
import { ListMonsters } from '@/components/listMonsters';
import { AppShell } from '@/components/layouts';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container w={'100vw'} h={'100vh'}>
        <AppShell pageTitle="Battle" toolbar={<AddMonster />}>
          <ListMonsters />
        </AppShell>
      </Container>
    </>
  );
}
